org: chauchuty
app: aws-medcloud
service: aws-medcloud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  api:
    handler: handler.patient
    events:
      -  httpApi: '*'
      
plugins:
  - serverless-offline